#!/bin/sh

if ip addr show dev eth0 | awk '/link\/ether/ {print $2}' | grep -q '29:f7:b5'; then
  uci set system.@system[0].hostname='OpenWrt254'
  uci commit system

  uci set network.lan.ipaddr='192.168.2.254'
  uci commit network
fi

exit 0
