#GitHub CI action to build packages via SDK using official OpenWrt SDK Docker containers.
name: Build packages via OpenWrt SDK

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      bpackages:
        description: 'packages to build'
        required: true
        default: 'vim'

env:
  BUILD_PACKAGES: ${{ github.event.inputs.bpackages }}

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.release }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - 21.02-SNAPSHOT
        arch:
          - x86_64
          - aarch64_cortex-a53

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          PACKAGES: ${{ env.BUILD_PACKAGES }}
          EXTRA_FEEDS: src-git|packages_up|https://github.com/eearphon/packages_up.git src-git|passwall_packages|https://github.com/xiaorouji/openwrt-passwall-packages.git src-git|passwall|https://github.com/xiaorouji/openwrt-passwall.git src-git|passwall2|https://github.com/xiaorouji/openwrt-passwall2.git src-git|helloworld|https://github.com/fw876/helloworld.git

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch}}-packages
          #path: bin/packages/${{ matrix.arch }}/packages/*.ipk
          path: bin/*
