#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: OpenWrt Builder custom

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo_url;branch (https://github.com/Lienol/openwrt;22.03)'
        required: true
        default: 'https://github.com/coolsnowwolf/lede'
      diy-partx_suffix:
        description: 'diy-partx_SUFFIX.sh (Lienol_22.03)'
        required: false
        default: ''
      kernel_ver:
        description: 'kernel version'
        required: false
        default: ''
      checkout:
        description: 'checkout'
        required: false
        default: ''
      lanip:
        description: 'lan ip address'
        required: true
        default: '192.168.2.1'

env:
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1_${{ github.event.inputs.diy-partx_suffix }}.sh
  DIY_P2_SH: diy-part2_${{ github.event.inputs.diy-partx_suffix }}.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
 
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        eval $(echo '${{ github.event.inputs.repo }}' | awk -F";" '{print "var1="$1";var2="$2}')
        echo "REPO_URL=$var1" >> $GITHUB_ENV
        echo "REPO_BRANCH=$var2" >> $GITHUB_ENV
        var3=$(echo '${{ github.event.inputs.repo }}' | awk -F"/" '{print $4'})
        [ -n "$var2" ] && var2="_$var2"
        echo "OWNER=$var3" >> $GITHUB_ENV
        [ -n "${{ github.event.inputs.diy-partx_suffix }}" ] || echo "DIY_P1_SH=diy-part1_${var3}${var2}.sh" >> $GITHUB_ENV
        [ -n "${{ github.event.inputs.diy-partx_suffix }}" ] || DIY_P2_SH=diy-part2_${var3}${var2}.sh
        echo "SUFFIX=${var3}${var2}" >> $GITHUB_ENV
        echo "$GITHUB_ENV"

    - name: Clone source code
      run: |
        pwd
        ls -l
        echo GITHUB_ENV $GITHUB_ENV
