name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  conditional-env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Set Environment Variable Conditionally
      run: |
        if [ "{${{ github.ref_name }}" == "main" ]; then
          echo "##[set-env name=MY_VARIABLE;value=MainBranchValue]"
        else
          echo "##[set-env name=MY_VARIABLE;value=OtherBranchValue]"
        fi
