#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: OpenWrt Builder custom

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      repourl:
        description: 'repo url(https://github.com/Lienol/openwrt)'
        required: true
        default: 'https://github.com/coolsnowwolf/lede'
      repobranch:
        description: 'repo branch(22.03 23.05 main)'
        required: true
        default: 'master'
      diy-partx_suffix:
        description: 'diy-partx_suffix.sh'
        required: true
        default: 'lede'
      lanip:
        description: 'lan ip address'
        required: true
        default: '192.168.2.1'

env:
  REPO_URL: ${{ github.event.inputs.repourl }}
  REPO_BRANCH: ${{ github.event.inputs.repobranch }}
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1_${{ github.event.inputs.diy-partx_suffix }}.sh
  DIY_P2_SH: diy-part2_${{ github.event.inputs.diy-partx_suffix }}.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 100
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
