name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday
  MY_ENV_VAR: ${{ if eq(variables.configuration, 'production') }}"production-value"${{ else }}"staging-value"${{ endif }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          cat /etc/os-release
        env:
          First_Name: Mona
