name: Print Environment Variables
 
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      repourl:
        description: 'repo_url;branch (https://github.com/Lienol/openwrt;22.03)'
        required: true
        default: 'https://github.com/coolsnowwolf/lede'
      lanip:
        description: 'lan ip address'
        required: true
        default: '192.168.2.1'

env:
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
 
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        echo $DIY_P1_SH
        eval $(echo '${{ github.event.inputs.repourl }}' | awk -F";" '{print "var1="$1";var2="$2}')
        echo "REPO_URL=$var1" >> $GITHUB_ENV
        echo "REPO_BRANCH=$var2" >> $GITHUB_ENV
        var3=$(echo '${{ github.event.inputs.repourl }}' | awk -F"/" '{print $4'})
        [ -n "$var2" ] && var2="_$var2"
        echo "OWNER=$var3" >> $GITHUB_ENV
        echo "DIY_P1_SH=diy-part1_${var3}${var2}.sh" >> $GITHUB_ENV
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Print Environment Variables
      run: |
        echo $DIY_P1_SH
        echo "DIY_P1_SH=$DIY_P1_SH" >> $GITHUB_ENV

    - name: Print again
      run: |
        echo ${{ env.DIY_P1_SH }}
        echo ${{ env.REPO_URL }}
        echo ${{ env.REPO_BRANCH }}
