name: Greeting on variable day

on:
  workflow_dispatch
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "poc"
        type: choice
        options:
          - poc
          - non-poc

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          cat /etc/os-release
        env:
          First_Name: Mona
