name: Print Environment Variables
 
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      repourl:
        description: 'repo(https://github.com/Lienol/openwrt)'
        required: true
        default: 'https://github.com/coolsnowwolf/lede'
      repobranch:
        description: 'branch(22.03 23.05 main)'
        required: true
        default: 'master'
      lanip:
        description: 'lan ip address'
        required: true
        default: '192.168.2.1'

env:
  REPO_URL: ${{ github.event.inputs.repourl }}
  REPO_BRANCH: ${{ github.event.inputs.repobranch }}
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1_other_$REPO_BRANCH.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
 
jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
    - name: Print Environment Variables
      run: printenv
